# Generated by Django 2.2.11 on 2020-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ifYouveNeverBeenHereTryThisFirst',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
