# Generated by Django 2.2.11 on 2020-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurant_ifyouveneverbeenheretrythisfirst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ifYouveNeverBeenHereTryThisFirst',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='If youve never been here before, try this'),
        ),
    ]
