# Generated by Django 2.1.15 on 2020-03-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200320_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivers',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Takeout', 'TakeOut')], default='Takeout', max_length=10),
        ),
    ]
