# Generated by Django 2.1.15 on 2020-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200320_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivers',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('TAKEOUT', 'Take Out')], default='TAKEOUT', max_length=10),
        ),
    ]
